[package]
name = "epub_internals"
version = "0.0.1"
authors = ["Daniel Garcia Moreno <danigm@wadobo.com>"]

[dependencies]
libc = "0.2"
epub = "1.0.3"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.1"

[lib]
name = "epub_internals"
crate-type = ["staticlib"]
