stages:
  - build

variables:
  FEDORA_DEPENDENCIES:
    gcc
    libsoup3-devel
    glib2-devel
    libxml2-devel
    libarchive-devel
    gobject-introspection-devel
    meson
    git

build-fedora:
  image: fedora:latest
  stage: build
  except:
    - tags
  before_script:
    - dnf update -y --nogpgcheck
    - dnf -y install --nogpgcheck $FEDORA_DEPENDENCIES
  script:
    - meson _build -Dwidget=false
    - ninja -C _build dist
