include:
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build-gnomeos"              # <1.>
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"   # <2.>
  - component: "gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master"
  - project: "gnome/citemplates"
    file: "templates/default-rules.yml"

stages:
  - "build"
  - "release"

variables:
  MESON_BUILD_DIR: "_builddir"
  TARBALL_ARTIFACT_PATH: "${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"
